# TODO: Change source to official ROS Dockerhub images once updated

FROM osrf/ros:noetic-desktop-full as jdeassets

# Install basic packages
RUN apt-get update && apt-get install -q -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install JdeRobot Assets

RUN git clone https://github.com/shreyasgokhale/assets /jderobot && cd /jderobot

RUN mkdir /jderobot/build
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && cd /jderobot/build && cmake ../jderobot_assets/ && make install"