# Jderobot Assets

FROM ros:noetic-ros-base as jdeassets

# Install basic packages
RUN apt-get update && apt-get install -q -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Pin the repo to master branch
ADD https://api.github.com/repos/shreyasgokhale/assets/git/refs/heads/noetic-master noetic-master.json

# Install JdeRobot Assets
RUN git clone https://github.com/shreyasgokhale/assets /jderobot && cd /jderobot
RUN mkdir /jderobot/build
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && cd /jderobot/build && cmake ../jderobot_assets/ && make install"


# Academy Image
FROM ros:noetic
COPY --from=jdeassets /opt/jderobot/ /opt/jderobot

## MESA
#RUN apt-get update && apt-get install -q -y \
#    ros-noetic-jderobot-assets \
#    && rm -rf /var/lib/apt/lists/*

# Sourcing
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash"
RUN /bin/bash -c "echo "source /opt/jderobot/share/jderobot/gazebo/assets-setup.sh" >> ~/.bashrc"
RUN /bin/bash -c "echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc"

# MESA
RUN apt-get update && apt-get install -q -y \
    x11-apps mesa-utils libgl1-mesa-glx libgl1-mesa-glx libgl1-mesa-dri \
    && rm -rf /var/lib/apt/lists/*

# ROS deps
RUN apt-get update && apt-get install -q -y \
    ros-noetic-mavros \
    && rm -rf /var/lib/apt/lists/*

# Install basic packages
RUN apt-get update && apt-get install -q -y \
    git qt5-default \
    && rm -rf /var/lib/apt/lists/*

#ROS again changed the images, so we have to install gazebo from scrach
#RUN /bin/bash -c "curl -sSL http://get.gazebosim.org | sh"


# NEW
# setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743

# setup sources.list
RUN . /etc/os-release \
    && echo "deb http://packages.osrfoundation.org/gazebo/$ID-stable `lsb_release -sc` main" > /etc/apt/sources.list.d/gazebo-latest.list

# install gazebo packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    gazebo11=11.0.0-2* \
    && rm -rf /var/lib/apt/lists/*


# Install gazebo ros packages
RUN apt-get update && apt-get install -q -y \
    git ros-noetic-gazebo-ros \
    && rm -rf /var/lib/apt/lists/*

# Install Kobuki Messages
RUN /bin/bash -c "git clone https://github.com/yujinrobot/kobuki_msgs /catkin_ws/src/kobuki"

RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && cd /catkin_ws && catkin_make install -DCMAKE_INSTALL_PREFIX=/opt/ros/noetic install"

#COPY development/amazon_exercise_dep /deps
#
#RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && mkdir /deps/build && cd /deps/build && cmake ../ && make install"

RUN apt-get update && apt-get install -q -y \
    python3-pip ros-noetic-navigation ros-noetic-gazebo-plugins\
    && rm -rf /var/lib/apt/lists/*


# TODO: Copy => mount
COPY ros1/exercises /exercises
RUN pip3 install -r /exercises/requirements-slim.txt


# Until jderobot/assets is updated
COPY development/model.sdf /opt/jderobot/share/jderobot/gazebo/models/amazon_warehouse_robot/model.sdf

COPY docker/ros_entrypoint.sh /
RUN chmod 755 /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
